package com.zhou.model;

import java.util.Date;

public class Activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.spend
     *
     * @mbggenerated
     */
    private String spend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.theme
     *
     * @mbggenerated
     */
    private String theme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.location
     *
     * @mbggenerated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.need_person
     *
     * @mbggenerated
     */
    private String needPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.created_by_name
     *
     * @mbggenerated
     */
    private String createdByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.created_by_id
     *
     * @mbggenerated
     */
    private Integer createdById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.introduce
     *
     * @mbggenerated
     */
    private String introduce;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.id
     *
     * @return the value of activity.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.id
     *
     * @param id the value for activity.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.created_at
     *
     * @return the value of activity.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.created_at
     *
     * @param createdAt the value for activity.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.spend
     *
     * @return the value of activity.spend
     *
     * @mbggenerated
     */
    public String getSpend() {
        return spend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.spend
     *
     * @param spend the value for activity.spend
     *
     * @mbggenerated
     */
    public void setSpend(String spend) {
        this.spend = spend == null ? null : spend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.theme
     *
     * @return the value of activity.theme
     *
     * @mbggenerated
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.theme
     *
     * @param theme the value for activity.theme
     *
     * @mbggenerated
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.location
     *
     * @return the value of activity.location
     *
     * @mbggenerated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.location
     *
     * @param location the value for activity.location
     *
     * @mbggenerated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.need_person
     *
     * @return the value of activity.need_person
     *
     * @mbggenerated
     */
    public String getNeedPerson() {
        return needPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.need_person
     *
     * @param needPerson the value for activity.need_person
     *
     * @mbggenerated
     */
    public void setNeedPerson(String needPerson) {
        this.needPerson = needPerson == null ? null : needPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.created_by_name
     *
     * @return the value of activity.created_by_name
     *
     * @mbggenerated
     */
    public String getCreatedByName() {
        return createdByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.created_by_name
     *
     * @param createdByName the value for activity.created_by_name
     *
     * @mbggenerated
     */
    public void setCreatedByName(String createdByName) {
        this.createdByName = createdByName == null ? null : createdByName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.created_by_id
     *
     * @return the value of activity.created_by_id
     *
     * @mbggenerated
     */
    public Integer getCreatedById() {
        return createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.created_by_id
     *
     * @param createdById the value for activity.created_by_id
     *
     * @mbggenerated
     */
    public void setCreatedById(Integer createdById) {
        this.createdById = createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.introduce
     *
     * @return the value of activity.introduce
     *
     * @mbggenerated
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.introduce
     *
     * @param introduce the value for activity.introduce
     *
     * @mbggenerated
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }
}