package com.zhou.model;

public class ArticleWithBLOBs extends Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.maincontent
     *
     * @mbggenerated
     */
    private String maincontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.img
     *
     * @mbggenerated
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.maincontent
     *
     * @return the value of article.maincontent
     *
     * @mbggenerated
     */
    public String getMaincontent() {
        return maincontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.maincontent
     *
     * @param maincontent the value for article.maincontent
     *
     * @mbggenerated
     */
    public void setMaincontent(String maincontent) {
        this.maincontent = maincontent == null ? null : maincontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content
     *
     * @return the value of article.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content
     *
     * @param content the value for article.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.img
     *
     * @return the value of article.img
     *
     * @mbggenerated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.img
     *
     * @param img the value for article.img
     *
     * @mbggenerated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }
}