package com.zhou.model;

public class Joinme {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joinme.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joinme.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joinme.activityid
     *
     * @mbggenerated
     */
    private Integer activityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joinme.id
     *
     * @return the value of joinme.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joinme.id
     *
     * @param id the value for joinme.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joinme.userid
     *
     * @return the value of joinme.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joinme.userid
     *
     * @param userid the value for joinme.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joinme.activityid
     *
     * @return the value of joinme.activityid
     *
     * @mbggenerated
     */
    public Integer getActivityid() {
        return activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joinme.activityid
     *
     * @param activityid the value for joinme.activityid
     *
     * @mbggenerated
     */
    public void setActivityid(Integer activityid) {
        this.activityid = activityid;
    }
}