package com.zhou.dao;

import com.zhou.model.Joinme;
import org.apache.ibatis.annotations.Param;

import java.util.List;
public interface JoinmeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joinme
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joinme
     *
     * @mbggenerated
     */
    int insert(Joinme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joinme
     *
     * @mbggenerated
     */
    int insertSelective(Joinme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joinme
     *
     * @mbggenerated
     */
    Joinme selectByPrimaryKey(Integer id);

    List<Joinme> selectAllbyactivityid(Integer activityid);

    List<Joinme> selectAllbyUserid(Integer userid);

    List<Joinme> selectByAllid(@Param("activityid")Integer activityid,@Param("userid") Integer userid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joinme
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Joinme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joinme
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Joinme record);
}
